### ISSUE TITLE
Preventing website from going offline.

### ISSUE THREAD

**Issue by bjedrzejewski** [chrisprice/t-d3fc#63]

**Comment by chrisprice** [comment]
Thanks for the heads up, the GIF generation service failed to restart after the hosting provider power cycled the box for a backup.

**Comment by chrisprice** [comment]
The main t-d3fc service then couldn't be started because it was trying to create a network link to an unknown container (even though the service supports running without the gif generation service). I'll need to dig a bit deeper to find out -
- [x] why the gif generation service didn't come back to life
- [ ] how to break the start-up dependency between them

**Comment by chrisprice** [comment]
I'd failed to enable the service so it was only started when I did it manually :-1: 

```
sudo systemctl enable selector-to-gif.service
```

**Comment by chrisprice** [comment]
User defined networking seems to be the way to break the link. I'll need to keep digging.

**Comment by chrisprice** [comment]
Closing as the site seems to have been stable for a while now
