### ISSUE TITLE
Use http referer

### ISSUE THREAD

**Issue by mypalmike** [chrisprice/t-d3fc#67]
When clicking on the t.d3fc.io link from a twitter status page, e.g.:

https://twitter.com/joel_w_smith/status/695201842968543232

... the server could potentially extract the status id from the referer http header and redirect to the associated t.d3fc.io status page (https://t.d3fc.io/status/695201842968543232) rather than the index page.

**Comment by chrisprice** [comment]
I like the idea but I'm not sure how to deal with the intermediate URLs that Twitter uses. E.g. if I click through to joel_w_smith's status, then the URL shows as https://t.co/nzZlSrVVnA. I'm pretty sure that means that the server will see that URL rather than the original status URL. Do you know a way to resolve that URL back to the status?

**Comment by mypalmike** [comment]
I'm not 100% sure you'd get the original referer url. And after posting this, I ended up realizing the feature  I really wanted is already there (the direct link in the tweet). So I'll just close this. This is a really cool project!

**Comment by chrisprice** [comment]
Thanks :)
